version: '3.8'
services:
  dev-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nestjs-drizzle
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    profiles:
      - dev
  test-db:
    image: mysql:latest
    ports:
      - "33306:3306"
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DBNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    profiles:
      - test